# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    env: prod
    instance:
        hostname: localhost
        appname: podiumRegistry
        prefer-ip-address: true
    server:
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://admin:${security.user.password:admin}@localhost:8761/eureka/

podium:
    security:
        authentication:
            jwt:
                secret: d6877ac45344bb624472a12dd83bb6b3b7e63113
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: catalog
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
        spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
            enabled: false
            # edit spring.metrics.export.delay-millis to set report frequency

spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    cloud:
        config:
            server:
                git:
                    # sample prod config using the central-directory folder in the podium-registry github repos
                    #uri: git@github.com:thehyve/bbmri-podium-config.git
                    uri: https://github.com/thehyve/bbmri-podium-config
                    searchPaths: '{application}'
                    username: # set via spring.cloud.server.git.username env var
                    password:
                prefix: /config
            name: podiumRegistry
    thymeleaf:
        cache: true

security:
    user:
        name: admin
        password: admin
        role: USER,ADMIN

server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
